name: iOS Client - EAS Build (migrated to EAS)

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
  push:
    branches: [main, sdk-*]
    paths:
      - apps/eas-expo-go/**
      - apps/expo-go/ios/**
      - tools/src/dynamic-macros/**
      - tools/src/commands/IosGenerateDynamicMacros.ts
      - secrets/**
      - fastlane/**
      - Gemfile.lock
  schedule:
    - cron: '20 5 * * *' # 5:20 AM UTC time every day

concurrency:
  group: ${{ workflow.filename }}-${{ github.ref }}
  cancel_in_progress: true

# note that there are also hooks in the `scripts` directory that run at different moments of the build process such as checking out the react-native submodule
jobs:
  create-android-credentials:
    # defaults:
    #   run:
    #     working_directory: ./apps/eas-expo-go
    steps:
      - name: Generate local credentials.json
        run: |
          cat >credentials.json <<EOL
          {
            "android": {
              "keystore": {
                "keystorePath": "release.keystore",
                "keystorePassword": "$ANDROID_KEYSTORE_PASSWORD",
                "keyAlias": "ExponentKey",
                "keyPassword": "$ANDROID_KEY_PASSWORD"
              }
            }
          }
          EOL
          echo $ANDROID_KEYSTORE_B64 | base64 -d > release.keystore
        env:
          ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

  build-ios:
    # TODO vonovak: the original GH action ran conditionally https://github.com/expo/expo/pull/25607 - not able to express that with EAS Workflows as of 8/25
    name: iOS Client Build
    type: build
    env:
      EAS_BUILD_PROFILE: unversioned-client
    params:
      platform: ios
      profile: unversioned-client
  build-android:
    needs: [create-android-credentials]
    name: Android Client Build
    type: build
    env:
      EAS_BUILD_PROFILE: unversioned-client
    params:
      platform: android
      profile: unversioned-client
# TODO vonovak: the following conditional probably isn't supported in workflows
#  notify_failure:
#    name: 🔔 Notify on Slack
#    after: [build]
#    if: failure() && (github.event_name == 'schedule' || github.event.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/heads/sdk-'))
#    type: slack
#    params:
#      webhook_url: ${{ secrets.slack_webhook_ios }}
#      message: 'Expo Go (iOS) build failed'
